[package]
name = "frustracean"
version = "0.1.0"
authors = ["J"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
speedy2d = "1.1.0"
wikipedia = "0.3.4"
regex = "1.5"
rand = "0.7.2"
itertools = "0.10.1"